name: python_gnu_parallel
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - ca-certificates=2020.6.20=hecda079_0
  - cairo=1.16.0=h3fc0475_1005
  - certifi=2020.6.20=py38h32f6830_0
  - click=7.1.2=pyh9f0ad1d_0
  - cycler=0.10.0=py_2
  - faker=4.1.2=py_0
  - fontconfig=2.13.1=h1056068_1002
  - freetype=2.10.2=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.65.0=h6f030ca_0
  - icu=67.1=he1b5a44_0
  - jpeg=9d=h516909a_0
  - kiwisolver=1.2.0=py38hbf85e49_0
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=hc38a660_9
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_15
  - libgfortran-ng=7.5.0=hdf63c60_15
  - libgomp=9.3.0=h24d8f2e_15
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_4
  - libpng=1.6.37=hed695b0_2
  - libstdcxx-ng=9.3.0=hdf63c60_15
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=h68273f3_2
  - lz4-c=1.9.2=he1b5a44_2
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py38h91b0d89_0
  - nano=2.9.8=hddfc1eb_1001
  - ncurses=6.2=he1b5a44_1
  - numpy=1.19.1=py38h8854b6b_0
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_1
  - pcre=8.44=he1b5a44_0
  - pillow=7.2.0=py38h9776b28_1
  - pip=20.2.2=py_0
  - pixman=0.38.0=h516909a_1003
  - progress=1.5=py_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycairo=1.19.1=py38h323dad1_3
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.8.5=h4d41432_2_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.8=1_cp38
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py38h32f6830_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h4cf870e_0
  - text-unidecode=1.3=py_0
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py38h1e0a361_1
  - wheel=0.35.1=pyh9f0ad1d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.11=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1007
  - zstd=1.4.5=h6597ccf_2
